### PR TITLE
make wider by default

### PR DESCRIPTION
**Pull request by wsor4035**
does what it says on the tin

### CODE REVIEW

**Comment by mark-wiemer** [comment]
How many characters are shown on a row now vs then?

**Comment by wsor4035** [comment]
pretty sure its a variable width font, so the answer to that is some range

**Comment by mark-wiemer** [comment]
Sure, can you give some approximations though? Our goal should be around 80-90 characters per line, right?

**Comment by wsor4035** [comment]
this pr
"adding enough ore-bearing mods, however this particular idea refers more to the issue some people have of going on a mining".length
123

current
"the issue some people have of going on a mining expedition and coming back so loaded down with ores".length
99

https://dev.luanti.org/calinous-law/

**Review by mark-wiemer — APPROVED** [review]

**Pull request merged**
