### PR TITLE
Add spell-checker and start fixups

### PR DESCRIPTION
**Pull request by mark-wiemer**
Starts work on #83

- Only adds it locally, not to CI
- Add recommended Open VSX extension to provide info squiggles under misspelled words and other IDE support
- Adds installation and settings docs, requires Node.js
- Originally there were 3,300+ issues in the reader-facing "content" folder, this PR gets it down to ~2,200

### CODE REVIEW

**Comment by mark-wiemer** [comment]
Build is failing because the comment shortcode is added after Hugo 0.134.2. Current latest is Hugo 0.140, let me find when comment shortcode was added

**Comment by mark-wiemer** [comment]
Comment shortcode was added in Hugo 0.137.2 according to [M.M on StackOverflow](https://stackoverflow.com/a/79172858), ref also [M.M's profile](https://stackoverflow.com/users/1505939/m-m).

Gonna update the YML accordingly

**Review by rollerozxa — APPROVED** [review]
Good idea to add a spell-checker. The current corrections in the content look good. Will you be pushing more corrections to the branch or can this be merged as-is?

**Comment by mark-wiemer** [comment]
Will be incrementally adding more fixes in separate PRs for ease of reviews, yep :)

**Pull request merged**
