### PR TITLE
Remove redundant line with typo

### PR DESCRIPTION
**Pull request by mark-wiemer**

### CODE REVIEW

**Review by wsor4035 — COMMENTED** [review]
if thats redundant the whole content index should be removed

**Comment by mark-wiemer** [comment]
This line specifically feels out of place, it's got a typo, not capitalized, no ending period, and only points to the navigation bar, which is pretty standard for websites nowadays. The other part of this section, the link to terminology is valuable

**Comment by wsor4035** [comment]
> before you start, look here
......then do nothing???

**Review by wsor4035 — APPROVED** [review]
just merging this since it will be better than it was before i suppose

**Pull request merged**
