### PR TITLE
Set max width for images

### PR DESCRIPTION
**Pull request by grorp**
does what it says

### CODE REVIEW

**Comment by wsor4035** [comment]
dont think we should be doing this globally

**Comment by mark-wiemer** [comment]
Per discussion I do think this is a good bandaid while we learn how to do it locally

**Comment by grorp** [comment]
If you compare mapgen/evolution and mapgen/features (both pages with a lot of images) before and after this PR, you'll see that the pages are a lot more readable afterwards, since the text isn't interrupted as much. This may be a bandaid, but it's not too hacky and it improves things.

**Comment by mark-wiemer** [comment]
@grorp a screen recording might go a long way to prove that if there is any resistance ;)

**Comment by grorp** [comment]
Sure, why not :)

Compare the current version of https://dev.luanti.org/mapgen/evolution/ (bad) to the following screen recording taken on this PR (good), on an approx. 1920x1080 screen:

https://github.com/user-attachments/assets/90992548-4787-46fa-aef7-061bcc1cc3e2

**Comment by rollerozxa** [comment]
I pulled the change locally and looked at some other pages with images and such and I don't think it's that bad of a change. I'd say merge it, and if there's a page with images that it will not work well with we'll see when that page exists. :+1:

**Pull request merged**
